### ISSUE TITLE
Weird Artifacts

### ISSUE THREAD

**Issue by terhechte** [linebender/piet-metal#1]
Hey! you might already know about this, but I thought I'd still post it just it case it might be helpful. I'm running `piet-metal` on a 2016 MBP with a Radeon Pro 450. It works, but the SVG tiger has *a lot* of artefacts:

<img width="1136" alt="Screenshot 2019-05-09 at 08 53 27" src="https://user-images.githubusercontent.com/132234/57433121-ec048e00-7237-11e9-81cb-16bc1a26e531.png">

I thought it might be integrated chip so I used gfx-status to enforce the discrete GPU and ran it again. That didn't change it though as piet properly automatically uses the discrete device.

![Screenshot 2019-05-09 at 08 54 05](https://user-images.githubusercontent.com/132234/57433148-02aae500-7238-11e9-8d1a-39134fcbc89c.png)

Is this expected behaviour? Can I submit any other system info to help out? Great project, looking forward to where this is going!

**Comment by raphlinus** [comment]
Thanks for the report, it's certainly not expected behavior. It's almost certainly because I've made some assumptions about SIMD group size which can very from card to card - [PietRender.metal line 233](https://github.com/linebender/piet-metal/blob/master/TestApp/PietRender.metal#L233) is the most likely culprit, and there might be another place.

I'll try to replace that with logic that uses the correct attributes for kernel function input arguments (threads_per_simdgroup and so on).

**Comment by raphlinus** [comment]
Could you by any chance run the cardioid image (change comments in [make_test_scene](https://github.com/linebender/piet-metal/blob/master/src/lib.rs#L354))? That's a very revealing test for simdgroup issues.

**Comment by torarnv** [comment]
Seeing the same artefacts on an iMac Pro with a Radeon Pro Vega 56 8 GB. Here's the cardioid image:

![image](https://user-images.githubusercontent.com/7536/57464370-e1b8b300-727c-11e9-9fb0-cd60f2e28cfd.png)

**Comment by torarnv** [comment]
> It's almost certainly because I've made some assumptions about SIMD group size which can very from card to card - PietRender.metal line 233 is the most likely culprit, and there might be another place.

Not sure if that's the right approach, but changing the `16` constant to 4,8,32, or 64 did not affect things.

**Comment by terhechte** [comment]
<img width="1136" alt="934174A6-EF55-49CA-A436-2C77A6ACD132" src="https://user-images.githubusercontent.com/132234/57467877-a8d00c80-7283-11e9-8161-0a6ac72ae6dc.png">
Here’s my image. I hope that helps!

**Comment by raphlinus** [comment]
Thanks, it definitely helps. It suggests that the simd group might be 64 on that hardware. I'm going to redo the grid logic so that it should be able to handle just about any combination of grid and simd, but I'm finding it quite tricky.

**Comment by raphlinus** [comment]
I just pushed a PR, but don't yet have confidence it's the right fix. For one, I'm seeing a performance regression on Intel 640, and it also doesn't seem to work with a tile width of 4 (you'd never do this, but in theory it should work with any power-of-2). I'd appreciate one of you trying it on the cardioid and seeing what happens, as that will tell me whether it's on the right track.

**Comment by raphlinus** [comment]
I tried another approach, getting rid of SIMD and using threadgroups. I see a 10% perf regression ballpark, but it might be the way forward, for a number of reasons. For one, it's going to be easier to port to older graphics cards because it doesn't rely on simdgroup. Also, for some reason, #2 was causing the simdgroup size to go to 8, which seemed to be the cause of the perf regression. @kvark and I have been looking into that and haven't gotten any answers yet. In any case, my measurement with #3 is that the simdgroup size is 16.

I know #3 has some rough edges, but I'd *love* to see whether it fixes the problem, and also get performance numbers (from the shader profiler), if you can get those.

Thanks again for the reports!

**Comment by terhechte** [comment]
As mentioned on the other PR, #3 fixes the issue for me. Thanks for looking into this!
